// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYVT4AfUMAS1bCTY_jZZGxGlZ0qLwh8w8',
    appId: '1:1019070396536:android:54e27f83e97ba8227b958d',
    messagingSenderId: '1019070396536',
    projectId: 'advance-parking-system-my-fyp',
    databaseURL: 'https://advance-parking-system-my-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'advance-parking-system-my-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfIG4el7XJ7j4VaQO2ZqNK2L_Ih8kaeT8',
    appId: '1:1019070396536:ios:d3830034cc12535e7b958d',
    messagingSenderId: '1019070396536',
    projectId: 'advance-parking-system-my-fyp',
    databaseURL: 'https://advance-parking-system-my-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'advance-parking-system-my-fyp.appspot.com',
    iosBundleId: 'com.example.advanceParkingOurFyp',
  );
}
